### ISSUE TITLE
Project Feedback

### ISSUE THREAD

**Issue by kisyular** [kisyular/MI-449-SS17-740-css-spacing-and-layout-T7bJIb#1]
@egillespie Can you take a look at this? It's [hosted here](https://kisyular-kapm87bvfi5cut7bjib.surge.sh/) and meets the following criteria:

- [x] Demonstrate an understanding of the CSS we've learned so far in the class
- [x] Use Flexbox to create the layout of your page
- [x] Use `margin` and `padding` to create space in and between elements
- [x] Use display `block` and `inline-block` properly
- [x] Have fun and do your best to make it pretty, the result should be something you would show to a future employer

**Comment by egillespie** [comment]
Good job incorporating aspects of this lesson into your site! Since we've already reviewed your page together, I only have a few comments:

### `display: block` on `.progress span` is being overridden

Styling the `span` in a `.progress` meter is a pretty clever way to use `display: block`, but the style isn't actually having any effect. The `display: block` property for those `span` elements is actually being inherited from your `.show` style.

The good news is the `.show` style isn't needed, so you can remove the `class="show"` attribute from those `span` elements without any impact to your page!

### Your `display: inline-block` aren't actually doing anything

The `button` elements are already styled as `display: inline-block` because of Bootstrap, so setting `display: inline-block` on your `.inlineType` style isn't actually doing anything. 😕 

Similarly, the `display: inline-block` style on `.navbar .navbar-nav` isn't having any effect.

I think instead of trying to apply `display: inline-block` to elements already styled by Bootstrap, you could add a `footer` to the bottom of the page with a copyright and maybe some social media links. That may a good place to try out `display: inline-block` on an element such as `span`.

### General feedback

#### Navigation bar

I recommend removing the "Home" link from your navigation bar and floating the links to the right. The "Home" link is a bit redundant since your name also links to `/`, and putting less-often used links on the right makes your name stand out more.

#### Biography

This would be easier to read if you split it into two paragraphs. 👍 

---

After you’ve made your changes and pushed them to GitHub and your hosted site, give it a once-over to make sure it looks right, then comment back here and I’ll take another look.

Thanks! 🏎

**Comment by kisyular** [comment]
I added a footer to the bottom of the page with a copyright and social media links. Removed the "Home" link from your navigation bar and floated the links to the right.

**Comment by egillespie** [comment]
This looks great! I noticed that your `sign.css` file isn't minified, nor is it referencing the generated source map, but since you demonstrated both those features in `style.css`, you're good to go. We'll provide better ways to manage your Sass compilation in an upcoming lesson. 😉 

:shipit:
